<x-storefront.layout title="Giỏ hàng | O Út Đặc Sản Huế">
    <section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="{{ route('home') }}">Trang chủ</a><span>/</span><span>Giỏ hàng</span></div><span class="eyebrow">Đơn hàng của bạn</span><h1>Giỏ hàng</h1><p>Kiểm tra đúng món, khối lượng và số lượng trước khi điền thông tin nhận hàng.</p></div></section>
    <section class="section"><div class="container">
        @if ($errors->has('cart'))<div class="error-summary">{{ $errors->first('cart') }}</div>@endif
        @if (session('status'))<div class="secure-note text-success">{{ session('status') }}</div>@endif
        @if ($lines->isEmpty())
            <div class="empty-state"><span class="empty-state__icon"><x-storefront.ui.icon name="cart" /></span><h2>Giỏ hàng đang trống</h2><p>Chọn một vài món Huế nhà làm rồi quay lại đây nhé.</p><a class="btn btn--primary" href="{{ route('products.index') }}">Chọn sản phẩm</a></div>
        @else
            <div class="cart-layout"><div class="panel"><div class="panel__header"><h2>Sản phẩm đã chọn</h2></div><div class="panel__body cart-items">@foreach ($lines as $line) @php($variant = $line['variant'])<article class="cart-item"><x-storefront.ui.product-media :product="$variant->product" /><div><p class="eyebrow">{{ $variant->product->category?->name ?? 'Đặc sản Huế' }}</p><h2>{{ $variant->product->name }}</h2><p class="cart-item__variant">{{ $variant->label }}</p>@if (! $line['can_fulfill'])<p class="text-danger small">Số lượng hiện không đủ tồn kho.</p>@endif</div><div class="cart-item__actions"><form method="POST" action="{{ route('cart.update', $variant) }}" class="quantity-control">@csrf @method('PATCH')<label class="sr-only" for="quantity-{{ $variant->id }}">Số lượng</label><input id="quantity-{{ $variant->id }}" name="quantity" type="number" min="0" max="{{ min(99, $variant->stock_quantity) }}" value="{{ $line['quantity'] }}"><button class="btn btn--ghost btn--sm" type="submit">Cập nhật</button></form><strong class="cart-item__price">{{ number_format($line['line_total_vnd'], 0, ',', '.') }} đ</strong><form method="POST" action="{{ route('cart.destroy', $variant) }}">@csrf @method('DELETE')<button class="text-link small" type="submit">Bỏ</button></form></div></article>@endforeach</div></div><aside class="summary-card"><h2>Tóm tắt đơn</h2><div class="summary-lines"><div class="summary-line"><span>Tạm tính</span><strong>{{ number_format($subtotalVnd, 0, ',', '.') }} đ</strong></div><div class="summary-line"><span>Phí giao dự kiến</span><strong>Nhập địa chỉ ở bước sau</strong></div><div class="summary-line summary-line--total"><span>Tổng dự kiến</span><strong>{{ number_format($subtotalVnd, 0, ',', '.') }} đ + phí giao</strong></div></div><p class="small muted">Phí giao được tính theo tỉnh/thành và hiển thị rõ trước khi đặt hàng.</p><a class="btn btn--primary btn--lg btn--block" href="{{ route('checkout.create') }}">Tiến hành đặt hàng <x-storefront.ui.icon name="arrow-right" /></a><a class="text-link small" href="{{ route('products.index') }}">Tiếp tục mua hàng</a><div class="secure-note"><x-storefront.ui.icon name="shield" /> Giá và tồn kho sẽ được server kiểm tra lại khi tạo đơn.</div></aside></div>
        @endif
    </div></section>
</x-storefront.layout>