@props(['cartCount' => 0])
<header class="site-header">
    <div class="utility-bar"><div class="container utility-bar__inner"><span>Cam kết chất lượng</span><span>Nguyên liệu rõ ràng</span><span>Giao hàng toàn quốc</span><span class="utility-spacer"></span><a href="tel:0909123456">Hotline: 0909 123 456</a></div></div>
    <div class="container header-main">
        <a class="brand" href="{{ route('home') }}"><img class="brand__mark" src="{{ asset('assets/images/logo-mark.png') }}" alt="O Út"><span class="brand__text"><span class="brand__name">O Út</span><span class="brand__tagline">đặc sản Huế</span></span></a>
        <form class="search-bar" method="GET" action="{{ route('products.index') }}"><input name="q" type="search" placeholder="Tìm tôm chua, mắm ruốc..." value="{{ request('q') }}"><button type="submit" aria-label="Tìm kiếm"><x-icon name="search" /></button></form>
        <div class="header-actions"><a href="{{ route('orders.track.form') }}"><x-icon name="receipt" /> Tra cứu đơn</a><a class="btn btn--primary" href="{{ route('cart') }}"><x-icon name="cart" /> Giỏ hàng @if($cartCount)<span class="cart-badge">{{ $cartCount }}</span>@endif</a></div>
    </div>
    <nav class="main-nav"><div class="container main-nav__inner"><a href="{{ route('home') }}">Trang chủ</a><a href="{{ route('products.index') }}">Sản phẩm</a><a href="{{ route('about') }}">Về O Út</a><a href="{{ route('blog.index') }}">Cẩm nang & công thức</a><a href="{{ route('policy') }}">Chính sách</a><a href="{{ route('contact') }}">Liên hệ</a></div></nav>
    <div class="mobile-header"><button class="icon-btn" type="button" data-mobile-menu-button aria-expanded="false" aria-label="Mở menu"><x-icon name="menu" /></button><a class="brand" href="{{ route('home') }}"><img class="brand__mark" src="{{ asset('assets/images/logo-mark.png') }}" alt=""><span class="brand__text"><span class="brand__name">O Út</span><span class="brand__tagline">đặc sản Huế</span></span></a><a class="icon-btn" href="{{ route('cart') }}" aria-label="Giỏ hàng"><x-icon name="cart" /></a></div>
    <div class="mobile-menu" data-mobile-menu aria-hidden="true"><form class="search-bar" method="GET" action="{{ route('products.index') }}"><input name="q" type="search" placeholder="Tìm sản phẩm"><button><x-icon name="search" /></button></form><div class="mobile-menu__links"><a href="{{ route('home') }}">Trang chủ</a><a href="{{ route('products.index') }}">Sản phẩm</a><a href="{{ route('about') }}">Về O Út</a><a href="{{ route('blog.index') }}">Cẩm nang & công thức</a><a href="{{ route('policy') }}">Chính sách</a><a href="{{ route('contact') }}">Liên hệ</a></div></div>
</header>
<nav class="bottom-nav" aria-label="Điều hướng nhanh"><a href="{{ route('home') }}"><x-icon name="home" />Trang chủ</a><a href="{{ route('products.index') }}"><x-icon name="grid" />Sản phẩm</a><a href="{{ route('cart') }}"><x-icon name="cart" />Giỏ hàng</a><a href="{{ route('orders.track.form') }}"><x-icon name="receipt" />Tra cứu</a></nav>
